<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.7 on win32)" generated="20221128 12:58:37.314" rpa="false" schemaversion="3">
<suite id="s1" name="Clock-App" source="C:\Users\mujtaba.afzal\PycharmProjects\pythonProject\Tests\clock-app.robot">
<test id="s1-t1" name="OPEN_APPLICATION" line="6">
<kw name="Open clock" library="clock-app-variables">
<doc>Opens clock app</doc>
<kw name="Open Application" library="AppiumLibrary">
<arg>${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>automationName=UiAutomator2</arg>
<arg>newCommandTimeout=2500</arg>
<arg>appActivity=${Activity_NAME}</arg>
<arg>appPackage=${PACKAGE_NAME}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20221128 12:58:38.619" level="INFO">Could not connect to port 4723 on host 127.0.0.1</msg>
<msg timestamp="20221128 12:58:38.619" level="INFO">Could not get IP address for host: 127.0.0.1</msg>
<msg timestamp="20221128 12:58:40.676" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C24DA11E0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20221128 12:58:42.694" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C24DA14B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" starttime="20221128 12:58:44.720" endtime="20221128 12:58:44.720"/>
</kw>
<msg timestamp="20221128 12:58:44.720" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<status status="FAIL" starttime="20221128 12:58:37.599" endtime="20221128 12:58:44.720"/>
</kw>
<status status="FAIL" starttime="20221128 12:58:37.599" endtime="20221128 12:58:44.720"/>
</kw>
<kw name="Page Should Contain Element" library="AppiumLibrary">
<arg>${APP_HEADER}</arg>
<doc>Verifies that current page contains `locator` element.</doc>
<status status="NOT RUN" starttime="20221128 12:58:44.724" endtime="20221128 12:58:44.724"/>
</kw>
<kw name="Element Text Should Be" library="AppiumLibrary">
<arg>${APP_HEADER}</arg>
<arg>Clock</arg>
<doc>Verifies element identified by ``locator`` exactly contains text ``expected``.</doc>
<status status="NOT RUN" starttime="20221128 12:58:44.724" endtime="20221128 12:58:44.724"/>
</kw>
<status status="FAIL" starttime="20221128 12:58:37.599" endtime="20221128 12:58:44.724">Execution terminated by signal</status>
</test>
<test id="s1-t2" name="VERIFY_TABS_WORKING" line="10">
<tag>robot:exit</tag>
<status status="FAIL" starttime="20221128 12:58:44.724" endtime="20221128 12:58:44.724">Test execution stopped due to a fatal error.</status>
</test>
<status status="FAIL" starttime="20221128 12:58:37.314" endtime="20221128 12:58:44.724"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0" info="combined" combined="NOT robot:exit">NOT robot:exit</stat>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Clock-App">Clock-App</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221128 12:58:40.676" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C24DA11E0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20221128 12:58:42.694" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C24DA14B0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20221128 12:58:44.720" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
</errors>
</robot>
